# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Dependabot will only find requirements.txt files in the directory
  # specified, plus one level of subdirectories, therefore two separate entries
  # are required here. When updating a dependency, ensure that each package is
  # updated to the same version across both directories.
  - package-ecosystem: "pip"
    directory: "/code"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
  - package-ecosystem: "pip"
    directory: "/extensions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
