name: cwydsa
services:
  web:
    image: fruoccopublic.azurecr.io/rag-webapp
    ports:
      - "8080:80"
    env_file:
      - path: ../.env
        required: false
      - path: $AZD_ENV_FILE
        required: false
  admin:
    image: fruoccopublic.azurecr.io/rag-adminwebapp
    ports:
      - "8081:80"
    env_file:
      - path: ../.env
        required: false
      - path: $AZD_ENV_FILE
        required: false
  backend:
    image: fruoccopublic.azurecr.io/rag-backend
    ports:
      - "8082:80"
    env_file:
      - path: .env
        required: false
      - path: $AZD_ENV_FILE
        required: false
