name: cwydsa
services:
  web:
    image: fruoccopublic.azurecr.io/rag-webapp
    ports:
      - "8080:80"
    env_file:
      - path: ../.env
        required: false
      - path: $AZD_ENV_FILE
        required: false
  admin:
    image: fruoccopublic.azurecr.io/rag-adminwebapp
    ports:
      - "8081:80"
    environment:
      - BACKEND_URL=http://backend
      - FUNCTION_KEY=some-test-key
    env_file:
      - path: ../.env
        required: false
      - path: $AZD_ENV_FILE
        required: false
  backend:
    image: fruoccopublic.azurecr.io/rag-backend
    ports:
      - "8082:80"
    environment:
      - AzureWebJobsSecretStorageType=files
    env_file:
      - path: .env
        required: false
      - path: $AZD_ENV_FILE
        required: false
    volumes:
      -  ${HOST_DOCKER_FOLDER:-.}/function-host.json:/azure-functions-host/Secrets/host.json
