AZURE_STORAGE_CONFIG_CONTAINER_NAME = "config"
AZURE_STORAGE_CONFIG_FILE_NAME = "active.json"

COMPUTER_VISION_VECTORIZE_IMAGE_PATH = "/computervision/retrieval:vectorizeImage"
COMPUTER_VISION_VECTORIZE_IMAGE_REQUEST_METHOD = "POST"
