export const conversationResponseWithCitations = {
    answer: {
      answer:
        "Microsoft AI encompasses a wide range of technologies and solutions that leverage artificial intelligence to empower individuals and organizations. Microsoft's AI platform, Azure AI, helps organizations transform by bringing intelligence and insights to solve their most pressing challenges[doc2]. Azure AI offers enterprise-level and responsible AI protections, enabling organizations to achieve more at scale[doc8]. Microsoft has a long-term partnership with OpenAI and deploys OpenAI's models across its consumer and enterprise products[doc5]. The company is committed to making the promise of AI real and doing it responsibly, guided by principles such as fairness, reliability and safety, privacy and security, inclusiveness, transparency, and accountability[doc1]. Microsoft's AI offerings span various domains, including productivity services, cloud computing, mixed reality, conversational AI, data analytics, and more[doc3][doc6][doc4]. These AI solutions aim to enhance productivity, improve customer experiences, optimize business functions, and drive innovation[doc9][doc7]. However, the adoption of AI also presents challenges and risks, such as biased datasets, ethical considerations, and potential legal and reputational harm[doc11]. Microsoft is committed to addressing these challenges and ensuring the responsible development and deployment of AI technologies[doc10].",
      citations: [
        {
          content: "someContent",
          id: "doc_7ff8f57d63e2eebb0a3372db05153822fdee65e6",
          chunk_id: 7,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_7ff8f57d63e2eebb0a3372db05153822fdee65e6",
          chunk_id: 7,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",

          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_7ff8f57d63e2eebb0a3372db05153822fdee65e6",
          chunk_id: 7,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_14b4ad620c24c5a472f0c4505019c5370b814e17",
          chunk_id: 4,
          title:
            "/documents/MSFT_FY23Q4_10K_DOCUMENT_FOLDER_SRC_IMPORTANT_CHUNKS_LIST_VALID_CHUNKS_ACCESS_TO_MSFT_WINDOWS_BLOBS_CORE_WINDOWS.docx",
          filepath:
            "MSFT_FY23Q4_10K_DOCUMENT_FOLDER_SRC_IMPORTANT_CHUNKS_LIST_VALID_CHUNKS_ACCESS_TO_MSFT_WINDOWS_BLOBS_CORE_WINDOWS.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_7ff8f57d63e2eebb0a3372db05153822fdee65e6",
          chunk_id: 7,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_d85da45581d92f2ff59e261197d2c70c2b6f8802",
          chunk_id: 8,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_3a2261beeaf7820dfdcc3b0d51a58bd981555b92",
          chunk_id: 6,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_7ff8f57d63e2eebb0a3372db05153822fdee65e6",
          chunk_id: 7,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_3a2261beeaf7820dfdcc3b0d51a58bd981555b92",
          chunk_id: 6,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_0b803fe4ec1406115ee7f35a9dd9060ad5d905f5",
          chunk_id: 57,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
        {
          content: "someContent",
          id: "doc_0b803fe4ec1406115ee7f35a9dd9060ad5d905f5",
          chunk_id: 57,
          title: "/documents/MSFT_FY23Q4_10K.docx",
          filepath: "MSFT_FY23Q4_10K.docx",
          url: "document url",
          metadata: null,
        },
      ],
    },
    isActive: false,
    index: 2,
  };
