$schema: https://azuremlschemas.azureedge.net/latest/flow.schema.json
name: bring_your_own_data_chat_qna
display_name: Multi-Round Q&A on Your Data
type: chat
path: ./flow.dag.yaml
description: Create a chatbot that uses LLM and data from your own indexed files to ground multi-round question and answering capabilities in enterprise chat scenarios.
properties:
  promptflow.stage: prod
  promptflow.details.type: markdown
  promptflow.details.source: README.md
  promptflow.batch_inputs: samples.json
