"""Pillar: Stable Core
Phase:  6 (Functions blueprints / modular RAG indexing pipeline)

Build the Flex Consumption deploy artifact for the `function` service
at ``v2/build-functions/``. azd packages whatever lives in
``services.function.project`` (set to ``./build-functions`` in
``azure.yaml``), so this hook stages a layout that satisfies two
constraints the in-tree ``src/functions/`` source layout cannot:

1. The Azure Functions Python host imports the entry module from the
   *deploy root* (``/home/site/wwwroot/function_app.py``). Source files
   under ``v2/src/functions/`` use absolute imports of the form
   ``from functions.<sub>.<mod> import ...`` (pytest resolves these via
   ``pythonpath = ["src"]``). At deploy time the host's sys.path is
   ``/home/site/wwwroot``, not ``/home/site``, so ``functions`` must
   exist as a package directory **at** the deploy root. This script
   places ``function_app.py`` at the build root and copies the
   blueprint packages into a sibling ``functions/`` subdirectory with a
   marker ``__init__.py``.

2. The blueprints also import ``from backend.core.<mod>`` for shared
   settings, providers, and types. ``v2/src/backend/`` is copied to
   ``build-functions/backend/`` so the same import surface resolves.

The build directory is gitignored (``v2/.gitignore`` line 16) and is
recreated from scratch on every invocation -- never edit it by hand.

``requirements.txt`` is generated from the ``[project].dependencies``
array of ``v2/pyproject.toml`` so the deps stay in one place. ``pip``
on the Functions host resolves transitives. ``.funcignore`` is also
emitted from the script -- the layout is fully owned here, no
pre-staged helper files.
"""

import shutil
import sys
import tomllib
from pathlib import Path

_V2_ROOT = Path(__file__).resolve().parents[1]
_SRC_FUNCTIONS = _V2_ROOT / "src" / "functions"
_SRC_BACKEND = _V2_ROOT / "src" / "backend"
_PYPROJECT = _V2_ROOT / "pyproject.toml"
_BUILD = _V2_ROOT / "build-functions"

# Subpackages under v2/src/functions/ that get nested under
# build-functions/functions/ so `from functions.<sub>...` resolves at
# deploy time. Listed explicitly (rather than globbed) so a stray
# directory under src/functions/ -- a scratch dir, a __pycache__, a
# half-renamed module -- never silently lands in the deploy artifact.
_FUNCTION_SUBPACKAGES = (
    "add_url",
    "batch_push",
    "batch_start",
    "blob_event",
    "search_skill",
    "core",
)

# Files copied to the build root verbatim. function_app.py is the
# Functions host entry point; host.json is the runtime configuration.
_ROOT_FILES = ("function_app.py", "host.json")

_FUNCIGNORE = """\
# Generated by v2/scripts/prepackage_function.py -- do not edit by hand.
.git*
.venv
.vscode
__pycache__
*.pyc
*.pyo
tests
*.md
local.settings.json
"""

_PACKAGE_MARKER = '"""Pillar: Stable Core\nPhase:  6 (Functions blueprints / modular RAG indexing pipeline)\n"""\n'


def _ignore_caches(_dir: str, names: list[str]) -> list[str]:
    """``shutil.copytree`` filter: skip caches + test trees + scratch dirs."""
    return [
        n
        for n in names
        if n in {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "tests"}
        or n.endswith(".pyc")
    ]


def _stage_root_files() -> None:
    for name in _ROOT_FILES:
        src = _SRC_FUNCTIONS / name
        if not src.is_file():
            sys.stderr.write(f"prepackage: missing required file {src}\n")
            sys.exit(2)
        shutil.copy2(src, _BUILD / name)


def _stage_functions_subpackages() -> None:
    pkg_root = _BUILD / "functions"
    pkg_root.mkdir(parents=True, exist_ok=False)
    (pkg_root / "__init__.py").write_text(_PACKAGE_MARKER, encoding="utf-8")
    for sub in _FUNCTION_SUBPACKAGES:
        src = _SRC_FUNCTIONS / sub
        if not src.is_dir():
            sys.stderr.write(f"prepackage: missing subpackage {src}\n")
            sys.exit(2)
        shutil.copytree(src, pkg_root / sub, ignore=_ignore_caches)


def _stage_backend() -> None:
    if not _SRC_BACKEND.is_dir():
        sys.stderr.write(f"prepackage: missing {_SRC_BACKEND}\n")
        sys.exit(2)
    shutil.copytree(_SRC_BACKEND, _BUILD / "backend", ignore=_ignore_caches)


def _write_requirements() -> None:
    data = tomllib.loads(_PYPROJECT.read_text(encoding="utf-8"))
    deps = data["project"]["dependencies"]
    if not isinstance(deps, list) or not deps:
        sys.stderr.write("prepackage: pyproject.toml has empty [project].dependencies\n")
        sys.exit(3)
    body = "\n".join(str(d) for d in deps) + "\n"
    (_BUILD / "requirements.txt").write_text(body, encoding="utf-8")


def _write_funcignore() -> None:
    (_BUILD / ".funcignore").write_text(_FUNCIGNORE, encoding="utf-8")


def main() -> int:
    # Clear contents instead of removing the directory itself: on
    # Windows the directory handle is frequently held by VS Code's file
    # watcher or by Defender, which makes a top-level `rmtree` race.
    # Wiping the contents and recreating subtrees is portable and
    # avoids the WinError 32 "file in use" failure mode.
    _BUILD.mkdir(parents=True, exist_ok=True)
    for child in _BUILD.iterdir():
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()

    _stage_root_files()
    _stage_functions_subpackages()
    _stage_backend()
    _write_requirements()
    _write_funcignore()

    print(f"prepackage: staged {_BUILD}")
    print(f"  function_app.py + host.json at root")
    print(f"  functions/ subpackages: {', '.join(_FUNCTION_SUBPACKAGES)}")
    print(f"  backend/ copied from src/backend")
    print(f"  requirements.txt + .funcignore generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
