name: AZD Template Validation

on:
  schedule:
    - cron: '30 1 * * 4' # Every Thursday 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation:
    runs-on: ubuntu-latest
    environment: production
    name: azd template validation
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Set timestamp
        shell: bash
        run: echo "HHMM=$(date -u +'%H%M')" >> "$GITHUB_ENV"

      - name: Validate Azure Template
        uses: microsoft/template-validation-action@v0.4.3
        with:
          validateAzd: ${{ vars.TEMPLATE_VALIDATE_AZD }}
          validateTests: ${{ vars.TEMPLATE_VALIDATE_TESTS }}
          useDevContainer: ${{ vars.TEMPLATE_USE_DEV_CONTAINER }}
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}-${{ env.HHMM }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_DEV_COLLECT_TELEMETRY: ${{ vars.AZURE_DEV_COLLECT_TELEMETRY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print validation result
        run: cat ${{ steps.validation.outputs.resultFile }}
