name: Validate bicep templates
on:
  push:
    branches:
      - main
    paths:
      - "**/*.bicep"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.bicep"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@5582dae351efca428a496a2227b189b7317ed766 # preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        if: github.repository_owner == 'Azure-Samples'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
