name: Broken Link Checker

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/broken-links-checker.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Check Markdown Broken Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # For PR : Get only changed markdown files
      - name: Get changed markdown files (PR only)
        id: changed-markdown-files
        if: github.event_name == 'pull_request'
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          changed_files=$(git diff --name-only --diff-filter=ACMR "$BASE_SHA" "$HEAD_SHA" -- '*.md' | tr '\n' ' ' | sed 's/ *$//')
          if [ -n "$changed_files" ]; then
            echo "any_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "any_changed=false" >> "$GITHUB_OUTPUT"
          fi
          echo "all_changed_files=$changed_files" >> "$GITHUB_OUTPUT"

      - name: Skip - No Markdown Files Changed
        if: github.event_name == 'pull_request' && steps.changed-markdown-files.outputs.any_changed != 'true'
        run: echo "No markdown files changed. Skipping broken link check."

      # For PR: Check broken links only in changed files
      - name: Check Broken Links in Changed Markdown Files
        id: lychee-check-pr
        if: github.event_name == 'pull_request' && steps.changed-markdown-files.outputs.any_changed == 'true'
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: >
            --verbose --no-progress --exclude ^https?://
            ${{ steps.changed-markdown-files.outputs.all_changed_files }}
          failIfEmpty: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # For manual trigger: Check all markdown files in repo
      - name: Check Broken Links in All Markdown Files in Entire Repo (Manual Trigger)
        id: lychee-check-manual
        if: github.event_name == 'workflow_dispatch'
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: >
            --verbose --no-progress --exclude ^https?://
            '**/*.md'
          failIfEmpty: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
