name: WebApp Docker Image

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

jobs:
  docker-build-frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: fruoccopublic.azurecr.io
        username: fruoccopublic
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v4

    - name: Build the Frontend Docker image
      run:
        docker pull fruoccopublic.azurecr.io/rag-webapp:latest || true;
        docker build . --file docker/Frontend.Dockerfile --cache-from fruoccopublic.azurecr.io/rag-webapp:latest --tag fruoccopublic.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag fruoccopublic.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER fruoccopublic.azurecr.io/rag-webapp:latest;
        docker push fruoccopublic.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push fruoccopublic.azurecr.io/rag-webapp:latest;