name: Backend Docker Image

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

jobs:
  docker-build-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build-docker.yml
    with:
      registry: fruoccopublic.azurecr.io
      username: fruoccopublic
      app_name: rag-backend
      dockerfile: docker/Backend.Dockerfile
    secrets: inherit
