name: Admin Web App Docker Image

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

jobs:
  docker-build-admin:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build-docker.yml
    with:
      registry: fruoccopublic.azurecr.io
      username: fruoccopublic
      app_name: rag-adminwebapp
      dockerfile: docker/Admin.Dockerfile
      push: true
    secrets: inherit
