name: WebApp Docker Image

on:
  push:
    branches:
      - docker-build-github-action

jobs:
  docker-build-frontend:
    uses: ./.github/workflows/build-docker.yml
    with:
      registry: fruoccopublic.azurecr.io
      username: fruoccopublic
      app_name: rag-webapp
      dockerfile: docker/Frontend.Dockerfile
    secrets: inherit
