name: Docker Build without Push

on:
  pull_request:
    branches: [main]
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize
  merge_group:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: rag-adminwebapp
            dockerfile: docker/Admin.Dockerfile
          - app_name: rag-backend
            dockerfile: docker/Backend.Dockerfile
          - app_name: rag-webapp
            dockerfile: docker/Frontend.Dockerfile
    uses: ./.github/workflows/build-docker.yml
    with:
      registry: fruoccopublic.azurecr.io
      username: fruoccopublic
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: false
    secrets: inherit
