name: Daily Broken Link Check

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  lychee:
    name: Broken Link Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            '**/*.md'
          output: lychee/out.md   # ✅ Set output file here, not in args
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update GitHub Issue if broken links found
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Broken Links Detected"
          content-filepath: lychee/out.md
          labels: links
          update_existing: true
          issue-pattern: "Broken Links Detected"
