name: Daily Broken Link Check

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:      # Optional: allows manual run

jobs:
  lychee:
    name: Broken Link Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            --output lychee/out.md
            '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update GitHub Issue if broken links found
        if: failure()  # Only runs if Lychee exits with error (broken links found)
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "🚨 Broken Links Detected"
          content-filepath: lychee/out.md
          labels: bug, links
          assignees: your-github-username    # optional: assign to yourself
          update-existing: true              # ✅ Avoids duplicate issues
          issue-pattern: "Broken Links Detected"  # Matches existing issue title
