name: Daily Broken Link Check

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  broken-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            '**/*.md'
          output: lychee/out.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find existing broken-link issue
        uses: micalevisk/last-issue-action@v2
        id: find_issue
        with:
          state: open
          labels: link-checker

      - name: Create or update issue
        if: steps.lychee.outputs.exit_code != '0'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Broken Links Detected"
          content-filepath: lychee/out.md
          labels: link-checker
          issue-number: ${{ steps.find_issue.outputs.issue_number }}
          
