name: Daily Broken Link Check

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  broken-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            '**/*.md'
          output: lychee/out.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if output file is empty
        id: check_file
        run: |
          if [ -s lychee/out.md ]; then
            echo "has_issues=true" >> $GITHUB_OUTPUT
          else
            echo "has_issues=false" >> $GITHUB_OUTPUT
          fi

      - name: Find existing issue
        id: find_issue
        if: steps.check_file.outputs.has_issues == 'true'
        uses: peter-evans/find-issue@v2
        with:
          title: "Broken Links Detected"
          state: open

      - name: Create or update GitHub Issue
        if: steps.check_file.outputs.has_issues == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Broken Links Detected"
          content-filepath: lychee/out.md
          labels: bug, links
          issue-number: ${{ steps.find_issue.outputs.issue-number }}
