name: Daily Broken Link Check

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            '**/*.md'
          output: lychee/out.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for broken links
        id: broken
        run: |
          if grep -q "✗" lychee/out.md; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Find existing broken-link issue
        if: steps.broken.outputs.found == 'true'
        uses: micalevisk/last-issue-action@v2
        id: find_issue
        with:
          state: open
          labels: broken-link-check

      - name: Create new issue if no existing one
        if: steps.broken.outputs.found == 'true' && steps.find_issue.outputs.issue_number == ''
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Broken Links Detected"
          content-filepath: lychee/out.md
          labels: broken-link-check

      - name: Update existing issue if found
        if: steps.broken.outputs.found == 'true' && steps.find_issue.outputs.issue_number != ''
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Broken Links Detected"
          content-filepath: lychee/out.md
          labels: broken-link-check
          issue-number: ${{ steps.find_issue.outputs.issue_number }}
