name: Comment coverage

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    name: Comment coverage
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@a1fe18e2b00c64a765568e2edb9f1706eb8fc88b
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: coverage-junit.xml
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          coverage-path-prefix: code/
          report-only-changed-files: true
