name: deploy to azure
on:
  push:
    branches: [ "main", "refactor-frontend-airbus" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: npm install, build, and test
      working-directory: ./code/frontend
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

        
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            #az storage blob upload-batch --account-name aasdoprontofrontend   -d $web -s ./build --overwrite --sas-token ${{ secrets.STORAGE_TOKEN }} 
            az storage blob upload-batch --account-name aasdoprontofrontend   -d $web -s ./build --overwrite --connection-string ${{ secrets.CONNECTION_STRING }} 
            #az storage blob sync -c $web --account-name aasdoprontofrontend  -s ./code/frontend/build --sas-token ${{ secrets.STORAGE_TOKEN }}
            
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "pronto-frontdoor" --name "pronto-frontdoor" --resource-group "rg-test-jt"

      # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
