# Workflow: Group Dependabot PRs
# Description:
# This GitHub Actions workflow automatically groups open Dependabot PRs by ecosystem (pip, npm).
# It cherry-picks individual PR changes into grouped branches, resolves merge conflicts automatically, and opens consolidated PRs.
# It also closes the original Dependabot PRs and carries over their labels and metadata.
# Improvements:
# - Handles multiple conflicting files during cherry-pick
# - Deduplicates entries in PR description
# - Avoids closing original PRs unless grouped PR creation succeeds
# - More efficient retry logic
# - Ecosystem grouping is now configurable via native YAML map
# - Uses safe namespaced branch naming (e.g. actions/grouped-...) to avoid developer conflict
# - Ensures PR body formatting uses real newlines for better readability
# - Adds strict error handling for script robustness
# - Accounts for tool dependencies (jq, gh) and race conditions
# - Optimized PR metadata lookup by preloading into associative array
# - Supports --dry-run mode for validation/testing without side effects
# - Note: PRs created during workflow execution will be picked up in the next scheduled run.

name: Group Dependabot PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  group-dependabot-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_BRANCH: "main"
      DRY_RUN: "false"
      # [customize] You can move GROUP_CONFIG to workflow inputs or YAML env for easier customization.
      GROUP_CONFIG_PIP: "backend"
      GROUP_CONFIG_NPM: "frontend"
      GROUP_CONFIG_YARN: "frontend"
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Install required tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: "jq gh"

      - name: Enable strict error handling
        shell: bash
        run: |
          set -euo pipefail

      - name: Fetch open Dependabot PRs targeting main
        id: fetch_prs
        run: |
          gh pr list \
            --search "author:dependabot[bot] base:$TARGET_BRANCH is:open" \
            --limit 100 \
            --json number,title,headRefName,labels,files,url \
            --jq '[.[] | {number, title, url, ref: .headRefName, labels: [.labels[].name], files: [.files[].path]}]' > prs.json
          cat prs.json

      - name: Validate prs.json
        run: |
          jq empty prs.json 2> jq_error.log || { echo "Malformed JSON in prs.json: $(cat jq_error.log)"; exit 1; }

      - name: Check if any PRs exist
        id: check_prs
        run: |
          count=$(jq length prs.json)
          echo "Found $count PRs"
          if [ "$count" -eq 0 ]; then
            echo "No PRs to group. Exiting."
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Exit early if no PRs
        if: steps.check_prs.outputs.skip == 'true'
        run: exit 0

      - name: Group PRs by ecosystem and cherry-pick with retry
        run: |
          # [customize] GROUP_CONFIG can be set via workflow env or inputs for easier maintenance.
          declare -A GROUP_CONFIG=(
            [pip]="${GROUP_CONFIG_PIP:-backend}"
            [npm]="${GROUP_CONFIG_NPM:-frontend}"
            [yarn]="${GROUP_CONFIG_YARN:-frontend}"
          )
          mkdir -p grouped
          jq -c '.[]' prs.json | while read pr; do
            ref=$(echo "$pr" | jq -r '.ref')
            number=$(echo "$pr" | jq -r '.number')
            group="misc"
            for key in "${!GROUP_CONFIG[@]}"; do
              if [[ "$ref" == *"$key"* ]]; then
                group="${GROUP_CONFIG[$key]}"
                break
              fi
            done
            echo "$number $ref $group" >> grouped/$group.txt
          done

          shopt -s nullglob
          grouped_files=(grouped/*.txt)

          if [ ${#grouped_files[@]} -eq 0 ]; then
            echo "No groups were formed. Exiting."
            exit 0
          fi

          # Renamed pr_data to pr_metadata_map for clarity
          declare -A pr_metadata_map
          while IFS=$'\t' read -r number title url labels; do
            pr_metadata_map["$number"]="$title|$url|$labels"
          done < <(jq -r '.[] | "\(.number)\t\(.title)\t\(.url)\t\(.labels | join(","))"' prs.json)

          for file in "${grouped_files[@]}"; do
            group_name=$(basename "$file" .txt)
            branch_name="actions/grouped-${group_name}-updates"
            git checkout -B "$branch_name"

            while read -r number ref group; do
              git fetch origin "$ref"
              if ! git cherry-pick FETCH_HEAD; then
                echo "Conflict found in $ref. Attempting to resolve."
                conflict_files=($(git diff --name-only --diff-filter=U))
                if [ ${#conflict_files[@]} -gt 0 ]; then
                  echo "Resolving conflicts in files: ${conflict_files[*]}"
                  for conflict_file in "${conflict_files[@]}"; do
                    echo "Resolving conflict in $conflict_file"
                    git checkout --theirs "$conflict_file"
                    git add "$conflict_file"
                  done
                  git cherry-pick --continue || {
                    echo "Failed to continue cherry-pick. Aborting."
                    git cherry-pick --abort
                    continue 2
                  }
                else
                  echo "No conflicting files found. Aborting."
                  git cherry-pick --abort
                  continue 2
                fi
              fi
            done < "$file"

            if [ "$DRY_RUN" == "true" ]; then
              echo "[DRY-RUN] Skipping git push for $branch_name"
            else
              # Use --force-with-lease for safer force-push
              git push --force-with-lease origin "$branch_name"
            fi

            new_lines=""
            while read -r number ref group; do
              IFS="|" read -r title url _ <<< "${pr_metadata_map["$number"]}"
              new_lines+="$title - [#$number]($url)\n"
            done < "$file"

            pr_title="chore(deps): bump grouped $group_name Dependabot updates"
            existing_url=$(gh pr list --head "$branch_name" --base "$TARGET_BRANCH" --json url --jq '.[0].url // empty')

            if [ -n "$existing_url" ]; then
              echo "PR already exists: $existing_url"
              pr_url="$existing_url"
              current_body=$(gh pr view "$pr_url" --json body --jq .body)
              existing_lines=$(echo "$current_body" | tr '\n' '\0')
              filtered_lines=""
              # Use printf '%b' for reliable newline handling
              while IFS= read -r -d '' line; do
                if ! echo "$existing_lines" | grep -qF -- "$line"; then
                  filtered_lines+="$line\n"
                fi
              done <<< "$(printf '%b' "$new_lines" | tr '\n' '\0')"
              new_body="$current_body$filtered_lines"
              if [ "$DRY_RUN" == "true" ]; then
                echo "[DRY-RUN] Would update PR body for $pr_url"
              else
                gh pr edit "$pr_url" --body "$new_body"
              fi
            else
              pr_body=$(printf "This PR groups multiple open PRs by Dependabot for %s.\n\n%b" "$group_name" "$new_lines")
              if [ "$DRY_RUN" == "true" ]; then
                echo "[DRY-RUN] Would create PR titled: $pr_title"
                echo "$pr_body"
                pr_url=""
              else
                pr_url=$(gh pr create \
                  --title "$pr_title" \
                  --body "$pr_body" \
                  --base "$TARGET_BRANCH" \
                  --head "$branch_name")
              fi
            fi

            if [ -n "$pr_url" ]; then
              for number in $(cut -d ' ' -f1 "$file"); do
                IFS="|" read -r _ _ labels <<< "${pr_metadata_map["$number"]}"
                IFS="," read -ra label_arr <<< "$labels"
                for label in "${label_arr[@]}"; do
                  if [ "$DRY_RUN" == "true" ]; then
                    echo "[DRY-RUN] Would add label $label to $pr_url"
                  else
                    gh pr edit "$pr_url" --add-label "$label"
                  fi
                done
                if [ "$DRY_RUN" == "true" ]; then
                  echo "[DRY-RUN] Would close PR #$number"
                else
                  gh pr close "$number" --comment "Grouped into $pr_url."
                fi
              done
              echo "Grouped PR created. Leaving branch $branch_name for now."
            else
              echo "Grouped PR was not created. Skipping closing of original PRs."
            fi
          done
