name: Check Broken links in PR

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important to allow full diff

      - name: Get changed Markdown files
        id: changed-files
        run: |
          git fetch origin main
          files=$(git diff --name-only origin/main...HEAD | grep '\.md$' || true)
          echo "md_files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Lychee on changed Markdown files (internal links only)
        if: steps.changed-files.outputs.md_files != ''
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            ${{ steps.changed-files.outputs.md_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
