name: Check Broken links in PR

on:
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Get changed Markdown files
        id: changed-files
        run: |
          echo "Fetching changed markdown files..."
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || true)
          echo "Changed Markdown files: $files"
          echo "md_files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Lychee only on internal links in changed .md files
        if: steps.changed-files.outputs.md_files != ''
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --verbose
            --exclude-mail
            --no-progress
            --exclude ^https?://
            ${{ steps.changed-files.outputs.md_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
