name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  test_package:
    name: Unit Tests
    runs-on: "ubuntu-20.04"
    steps:
        - uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
            architecture: x64
        - name: Install dependencies
          run: |
            pip install -r code/requirements.txt -r code/dev-requirements.txt
        - name: Run Python tests
          run: python -m pytest --rootdir=code -m "not azure"
